#!/bin/bash
#
# Copyright 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This helper script is used to access several Connector Manager functions
# from the command line.  This script sets up the Java classpath needed
# by the Connector Manager, then invokes the Connector Manager command
# processor.

# Usage: Manager [-?] [-v] [command] [options] [arguments]
#        -?, --help    Display the set of available commands
#        -v, --version Display the Connector Manager version
#
# To get help for a command, specify the command along with -? or --help
# For instance:
# % Manager MigrateStore --help

# The Connector Manager main class.
classname=com.google.enterprise.connector.manager.ManagerMain

pwd=`pwd`
pwdname=`basename "${pwd}"`
parentdir=`dirname "${pwd}"`
parentname=`basename "${parentdir}"`

# If there is a setenv file in the same directory as my script, then invoke
# it to set certain environment variables appropriate to this installation.
# For instance, JAVA_HOME or CLASSPATH.
# If the Connector requires JAR files not included in the Connector
# installation (for instance Documentum DFC JAR files), then you should
# specify those JAR files in the CLASSPATH environment variable.
# For instance:
# % export CLASSPATH="$CLASSPATH":"$DOCUMENTUM_SHARED"/dfc/dfc.jar:"$DOCUMENTUM_SHARED"/config
setenv=`dirname $0`/setenv
if [ -f "$setenv" ] ; then
  . "$setenv"
fi

# Locate a Java runtime. The Connector Manager requires Java 5 or better.
java=
if [ -n "$JAVA_HOME" ] ; then
  java="$JAVA_HOME"/bin/java
elif [ -n "$JRE_HOME" ] ; then
  java="$JRE_HOME"/bin/java
else
  java=`which java`
fi
if [ -z "${java}" ] ; then
  echo Please include a Java 5 or newer runtime on your program PATH,
  echo or specify a Java installation in the JAVA_HOME environment variable.
  exit -1
fi

# Locate the Tomcat 6 installation.  Note that this code requires a
# Tomcat 6 directory layout, which is much simplified over previous versions.
cathome="$CATALINA_HOME"
if [ -z "${cathome}" ] ; then
  if [ "${pwdname}" = "Scripts" ] ; then
    catjar=`find -H "${parentdir}"/Tomcat -name catalina.jar | head -1`
  else
    catjar=`find -H "${pwd}" -name catalina.jar | head -1`
  fi
  if [ -z "${catjar}" ] ; then
    echo Unable to locate the Apache Tomcat web application container.
    echo Please set the CATALINA_HOME and CATALINA_BASE environment
    echo variables appropriately.
    exit -1
  fi
  catlib=`dirname "${catjar}"`
  cathome=`dirname "${catlib}"`
fi
catbase="$CATALINA_BASE"
if [ -z "${catbase}" ] ; then
  catbase="${cathome}"
fi

# Locate the Connector Manager's WEB-INF directory, typically found at
# 'Tomcat/webapps/connector-manager/WEB-INF' in the Connector installation.
webinf="${catbase}/webapps/connector-manager/WEB-INF"
if [ ! -d "${webinf}" ] ; then
  if [ "${pwdname}" = "WEB-INF" -a "${parentname}" = "connector-manager" ]
  then
    webinf="${pwd}"
  elif [ "${pwdname}" = "Scripts" ] ; then
    webinf=`find -H "${parentdir}"/Tomcat -name WEB-INF | grep connector-manager | head -1`
  else
    webinf=`find -H "${pwd}" -name WEB-INF | grep connector-manager | head -1`
  fi
fi
if [ ! -d "${webinf}" ] ; then
  echo Unable to locate the Connector Manager web application directory.
  exit -1
fi

# Set the classpath to include all jars in the Connector Manager lib directory.
classpath="$CLASSPATH"
for jar in "${webinf}"/lib/*.jar ; do
  classpath="${classpath}":"${jar}"
done

# Add all the jars in the Tomcat lib directory.  This is where JDBC drivers
# should be installed.
for jar in "${cathome}"/lib/*.jar ; do
  classpath="${classpath}":"${jar}"
done

# The Connector Manager webapp directory is the parent of WEB-INF.
managerdir=`dirname "${webinf}"`

# Run the program.
"${java}" -Dmanager.dir="${managerdir}" -Dcatalina.base="${catbase}" -classpath "${classpath}" ${classname} "$@"

