// Copyright 2008 Google Inc.  All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.enterprise.security.connectors.formauth;

import com.google.enterprise.common.HttpClientInterface;
import com.google.enterprise.common.MockHttpClient;
import com.google.enterprise.common.MockHttpTransport;
import com.google.enterprise.connector.manager.Context;
import com.google.enterprise.connector.spi.AuthenticationResponse;
import com.google.enterprise.security.identity.AuthnDomainGroup;
import com.google.enterprise.security.identity.CredentialsGroup;
import com.google.enterprise.security.identity.CsvConfig;
import com.google.enterprise.security.identity.DomainCredentials;

import junit.framework.TestCase;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;

public class FormAuthConnectorTest extends TestCase {

  private final HttpClientInterface httpClient;
  private final CredentialsGroup cg;

  public FormAuthConnectorTest(String name) throws IOException, ServletException {
    super(name);
    Context.getInstance().setStandaloneContext(
        "source/webdocs/test/applicationContext.xml",
        Context.DEFAULT_JUNIT_COMMON_DIR_PATH);
    List<AuthnDomainGroup> adgs = CsvConfig.readConfigFile("testdata/mocktestdata/AuthSites.conf");
    cg = new CredentialsGroup(adgs.get(0));
    cg.autogenerateDomainCredentials();
    MockHttpTransport transport = new MockHttpTransport();
    transport.registerServlet(cg.getElements().get(0).getLoginUrl(),
                              new MockFormAuthServer.Server1());
    httpClient = new MockHttpClient(transport);
  }

  public void test1() {
    cg.setUsername("joe");
    cg.setPassword("plumber");
    DomainCredentials dCred = cg.getElements().get(0);
    FormAuthConnector connector = new FormAuthConnector(httpClient, "foo");
    AuthenticationResponse response = connector.authenticate(dCred);
    assertNotNull("Null response from authenticate()", response);
    assertTrue("Invalid response from authenticate()", response.isValid());
    assertTrue(dCred.getCookies().size() > 0);

    response = connector.authenticate(dCred);
    assertNotNull("Null response from authenticate()", response);
    assertFalse("Valid response from re-authenticate()", response.isValid());
  }
}
